import { useEffect, useState, type FormEvent } from 'react';
import { Archive, CheckCircle2, DatabaseBackup, KeyRound, Landmark, Palette, Plus, RotateCcw, Save } from 'lucide-react';
import type { AppSettings, Platform } from '../../shared/types';
import { errorMessage } from '../format';
import { Button } from '../components/ui/button';
import { Input } from '../components/ui/input';

export function SettingsPage({ onSettingsChange }: { onSettingsChange: (settings: AppSettings) => void }) {
  const [settings, setSettings] = useState<AppSettings | null>(null); const [platforms, setPlatforms] = useState<Platform[]>([]);
  const [startDate, setStartDate] = useState(''); const [colorMode, setColorMode] = useState<'us' | 'cn'>('us'); const [apiKey, setApiKey] = useState(''); const [newPlatform, setNewPlatform] = useState('');
  const [notice, setNotice] = useState(''); const [busy, setBusy] = useState('');
  const load = () => Promise.all([window.stockEarn.settings.get(), window.stockEarn.platforms.list(true)]).then(([nextSettings, nextPlatforms]) => { setSettings(nextSettings); setStartDate(nextSettings.startDate ?? ''); setColorMode(nextSettings.colorMode); setPlatforms(nextPlatforms); });
  useEffect(() => { void load(); }, []);

  async function saveGeneral() { setBusy('general'); setNotice(''); try { const next = await window.stockEarn.settings.update({ startDate, colorMode }); setSettings(next); onSettingsChange(next); setNotice('账本设置已保存'); } catch (reason) { setNotice(errorMessage(reason)); } finally { setBusy(''); } }
  async function saveKey() { setBusy('key'); setNotice(''); try { if (apiKey) { const test = await window.stockEarn.settings.testQuoteProvider(apiKey); if (!test.ok) throw new Error(test.message); } const next = await window.stockEarn.settings.update({ apiKey: apiKey || null }); setSettings(next); onSettingsChange(next); setApiKey(''); setNotice(apiKey ? 'API Key 已测试并加密保存' : 'API Key 已移除'); } catch (reason) { setNotice(errorMessage(reason)); } finally { setBusy(''); } }
  async function addPlatform(event: FormEvent) { event.preventDefault(); if (!newPlatform.trim()) return; try { await window.stockEarn.platforms.create({ name: newPlatform }); setNewPlatform(''); await load(); } catch (reason) { setNotice(errorMessage(reason)); } }
  async function togglePlatform(platform: Platform) { await window.stockEarn.platforms.archive({ id: platform.id, archived: !platform.archived }); await load(); }
  async function exportBackup() { setBusy('backup'); try { const result = await window.stockEarn.backup.export(); if (result.path) setNotice(`备份已保存到 ${result.path}`); } catch (reason) { setNotice(errorMessage(reason)); } finally { setBusy(''); } }
  async function restoreBackup() { if (!confirm('恢复备份会替换当前账本。应用会先自动保存一份恢复前备份，是否继续？')) return; setBusy('restore'); try { const result = await window.stockEarn.backup.restore(); if (result.restored) window.location.reload(); } catch (reason) { setNotice(errorMessage(reason)); setBusy(''); } }
  if (!settings) return <div className="page-loading"><span /><p>正在读取设置…</p></div>;
  return <div className="page settings-page"><header className="page-header"><div><p className="eyebrow">LEDGER SETTINGS</p><h1>设置</h1><p>管理账本起点、交易平台和本地数据。</p></div></header>{notice && <div className="notice-bar">{notice}</div>}
    <div className="settings-grid">
      <section className="settings-card"><div className="settings-card-title"><Landmark /><div><h2>账本规则</h2><p>起始日不能晚于已有交易。</p></div></div><div className="form-stack"><label>入市起始日<Input type="date" value={startDate} onChange={(e) => setStartDate(e.target.value)} /></label><Button variant="primary" className="align-self" onClick={saveGeneral} disabled={busy === 'general'}><Save size={16} />{busy === 'general' ? '保存中…' : '保存账本规则'}</Button></div></section>
      <section className="settings-card"><div className="settings-card-title"><Palette /><div><h2>盈亏颜色</h2><p>买卖标记始终使用蓝色和橙色。</p></div></div><div className="color-options"><button className={colorMode === 'us' ? 'active' : ''} onClick={() => setColorMode('us')}><span><i className="profit-swatch" />盈利绿色</span><small>美股习惯 · 推荐</small></button><button className={colorMode === 'cn' ? 'active' : ''} onClick={() => setColorMode('cn')}><span><i className="loss-swatch" />盈利红色</span><small>中国市场习惯</small></button></div><Button variant="secondary" className="align-self" onClick={saveGeneral}><Save size={16} />保存显示偏好</Button></section>
      <section className="settings-card span-two"><div className="settings-card-title"><KeyRound /><div><h2>最新参考价</h2><p>Twelve Data API Key 由 Windows 加密保存，不会写入备份。</p></div>{settings.hasApiKey && <span className="status-badge"><CheckCircle2 size={14} />已连接</span>}</div><div className="inline-form"><Input type="password" value={apiKey} onChange={(e) => setApiKey(e.target.value)} placeholder={settings.hasApiKey ? '输入新 Key 可替换；留空保存将移除' : '粘贴 Twelve Data API Key'} /><Button variant="secondary" onClick={saveKey} disabled={busy === 'key'}>{busy === 'key' ? '测试中…' : settings.hasApiKey ? '更新 Key' : '测试并保存'}</Button></div></section>
      <section className="settings-card span-two"><div className="settings-card-title"><Landmark /><div><h2>交易平台</h2><p>已发生交易的平台归档后仍会保留在历史记录中。</p></div></div><form className="inline-form" onSubmit={addPlatform}><Input value={newPlatform} onChange={(e) => setNewPlatform(e.target.value)} placeholder="添加平台，例如 IBKR" /><Button variant="primary"><Plus size={16} />添加</Button></form><div className="platform-list">{platforms.map((platform) => <div key={platform.id} className={platform.archived ? 'archived' : ''}><span className="platform-avatar">{platform.name.slice(0, 2).toUpperCase()}</span><strong>{platform.name}</strong><small>{platform.archived ? '已归档' : '使用中'}</small><Button variant="ghost" size="sm" onClick={() => togglePlatform(platform)}>{platform.archived ? <><RotateCcw size={14} />恢复</> : <><Archive size={14} />归档</>}</Button></div>)}</div></section>
      <section className="settings-card span-two"><div className="settings-card-title"><DatabaseBackup /><div><h2>本地备份</h2><p>导出交易、行情缓存和设置；API Key 不包含在内。</p></div></div><div className="backup-actions"><Button variant="secondary" onClick={exportBackup} disabled={busy === 'backup'}><DatabaseBackup size={16} />{busy === 'backup' ? '导出中…' : '导出备份'}</Button><Button variant="danger" onClick={restoreBackup} disabled={busy === 'restore'}><RotateCcw size={16} />{busy === 'restore' ? '恢复中…' : '从备份恢复'}</Button></div></section>
    </div>
  </div>;
}
